package com.education.generator;

import com.education.block.ModBlocks;

import net.fabricmc.fabric.api.datagen.v1.provider.FabricBlockLootSubProvider;
import net.fabricmc.fabric.api.datagen.v1.FabricPackOutput;
import net.minecraft.core.HolderLookup;
import java.util.concurrent.CompletableFuture;

public class EducationBlockLootTableProvider extends FabricBlockLootSubProvider {
	public EducationBlockLootTableProvider(FabricPackOutput dataOutput, CompletableFuture<HolderLookup.Provider> registryLookup) {
		super(dataOutput, registryLookup);
	}

	@Override
	public void generate() {
		dropSelf(ModBlocks.ELEMENT_UNKNOWN);
		dropSelf(ModBlocks.ELEMENT_H);
		dropSelf(ModBlocks.ELEMENT_HE);
		dropSelf(ModBlocks.ELEMENT_LI);
		dropSelf(ModBlocks.ELEMENT_BE);
		dropSelf(ModBlocks.ELEMENT_B);
		dropSelf(ModBlocks.ELEMENT_C);
		dropSelf(ModBlocks.ELEMENT_N);
		dropSelf(ModBlocks.ELEMENT_O);
		dropSelf(ModBlocks.ELEMENT_F);
		dropSelf(ModBlocks.ELEMENT_NE);
		dropSelf(ModBlocks.ELEMENT_NA);
		dropSelf(ModBlocks.ELEMENT_MG);
		dropSelf(ModBlocks.ELEMENT_AL);
		dropSelf(ModBlocks.ELEMENT_SI);
		dropSelf(ModBlocks.ELEMENT_P);
		dropSelf(ModBlocks.ELEMENT_S);
		dropSelf(ModBlocks.ELEMENT_CL);
		dropSelf(ModBlocks.ELEMENT_AR);
		dropSelf(ModBlocks.ELEMENT_K);
		dropSelf(ModBlocks.ELEMENT_CA);
		dropSelf(ModBlocks.ELEMENT_SC);
		dropSelf(ModBlocks.ELEMENT_TI);
		dropSelf(ModBlocks.ELEMENT_V);
		dropSelf(ModBlocks.ELEMENT_CR);
		dropSelf(ModBlocks.ELEMENT_MN);
		dropSelf(ModBlocks.ELEMENT_FE);
		dropSelf(ModBlocks.ELEMENT_CO);
		dropSelf(ModBlocks.ELEMENT_NI);
		dropSelf(ModBlocks.ELEMENT_CU);
		dropSelf(ModBlocks.ELEMENT_ZN);
		dropSelf(ModBlocks.ELEMENT_GA);
		dropSelf(ModBlocks.ELEMENT_GE);
		dropSelf(ModBlocks.ELEMENT_AS);
		dropSelf(ModBlocks.ELEMENT_SE);
		dropSelf(ModBlocks.ELEMENT_BR);
		dropSelf(ModBlocks.ELEMENT_KR);
		dropSelf(ModBlocks.ELEMENT_RB);
		dropSelf(ModBlocks.ELEMENT_SR);
		dropSelf(ModBlocks.ELEMENT_Y);
		dropSelf(ModBlocks.ELEMENT_ZR);
		dropSelf(ModBlocks.ELEMENT_NB);
		dropSelf(ModBlocks.ELEMENT_MO);
		dropSelf(ModBlocks.ELEMENT_TC);
		dropSelf(ModBlocks.ELEMENT_RU);
		dropSelf(ModBlocks.ELEMENT_RH);
		dropSelf(ModBlocks.ELEMENT_PD);
		dropSelf(ModBlocks.ELEMENT_AG);
		dropSelf(ModBlocks.ELEMENT_CD);
		dropSelf(ModBlocks.ELEMENT_IN);
		dropSelf(ModBlocks.ELEMENT_SN);
		dropSelf(ModBlocks.ELEMENT_SB);
		dropSelf(ModBlocks.ELEMENT_TE);
		dropSelf(ModBlocks.ELEMENT_I);
		dropSelf(ModBlocks.ELEMENT_XE);
		dropSelf(ModBlocks.ELEMENT_CS);
		dropSelf(ModBlocks.ELEMENT_BA);
		dropSelf(ModBlocks.ELEMENT_LA);
		dropSelf(ModBlocks.ELEMENT_CE);
		dropSelf(ModBlocks.ELEMENT_PR);
		dropSelf(ModBlocks.ELEMENT_ND);
		dropSelf(ModBlocks.ELEMENT_PM);
		dropSelf(ModBlocks.ELEMENT_SM);
		dropSelf(ModBlocks.ELEMENT_EU);
		dropSelf(ModBlocks.ELEMENT_GD);
		dropSelf(ModBlocks.ELEMENT_TB);
		dropSelf(ModBlocks.ELEMENT_DY);
		dropSelf(ModBlocks.ELEMENT_HO);
		dropSelf(ModBlocks.ELEMENT_ER);
		dropSelf(ModBlocks.ELEMENT_TM);
		dropSelf(ModBlocks.ELEMENT_YB);
		dropSelf(ModBlocks.ELEMENT_LU);
		dropSelf(ModBlocks.ELEMENT_HF);
		dropSelf(ModBlocks.ELEMENT_TA);
		dropSelf(ModBlocks.ELEMENT_W);
		dropSelf(ModBlocks.ELEMENT_RE);
		dropSelf(ModBlocks.ELEMENT_OS);
		dropSelf(ModBlocks.ELEMENT_IR);
		dropSelf(ModBlocks.ELEMENT_PT);
		dropSelf(ModBlocks.ELEMENT_AU);
		dropSelf(ModBlocks.ELEMENT_HG);
		dropSelf(ModBlocks.ELEMENT_TL);
		dropSelf(ModBlocks.ELEMENT_PB);
		dropSelf(ModBlocks.ELEMENT_BI);
		dropSelf(ModBlocks.ELEMENT_PO);
		dropSelf(ModBlocks.ELEMENT_AT);
		dropSelf(ModBlocks.ELEMENT_RN);
		dropSelf(ModBlocks.ELEMENT_FR);
		dropSelf(ModBlocks.ELEMENT_RA);
		dropSelf(ModBlocks.ELEMENT_AC);
		dropSelf(ModBlocks.ELEMENT_TH);
		dropSelf(ModBlocks.ELEMENT_PA);
		dropSelf(ModBlocks.ELEMENT_U);
		dropSelf(ModBlocks.ELEMENT_NP);
		dropSelf(ModBlocks.ELEMENT_PU);
		dropSelf(ModBlocks.ELEMENT_AM);
		dropSelf(ModBlocks.ELEMENT_CM);
		dropSelf(ModBlocks.ELEMENT_BK);
		dropSelf(ModBlocks.ELEMENT_CF);
		dropSelf(ModBlocks.ELEMENT_ES);
		dropSelf(ModBlocks.ELEMENT_FM);
		dropSelf(ModBlocks.ELEMENT_MD);
		dropSelf(ModBlocks.ELEMENT_NO);
		dropSelf(ModBlocks.ELEMENT_LR);
		dropSelf(ModBlocks.ELEMENT_RF);
		dropSelf(ModBlocks.ELEMENT_DB);
		dropSelf(ModBlocks.ELEMENT_SG);
		dropSelf(ModBlocks.ELEMENT_BH);
		dropSelf(ModBlocks.ELEMENT_HS);
		dropSelf(ModBlocks.ELEMENT_MT);
		dropSelf(ModBlocks.ELEMENT_DS);
		dropSelf(ModBlocks.ELEMENT_RG);
		dropSelf(ModBlocks.ELEMENT_CN);
		dropSelf(ModBlocks.ELEMENT_NH);
		dropSelf(ModBlocks.ELEMENT_FL);
		dropSelf(ModBlocks.ELEMENT_MC);
		dropSelf(ModBlocks.ELEMENT_LV);
		dropSelf(ModBlocks.ELEMENT_TS);
		dropSelf(ModBlocks.ELEMENT_OG);
	}
}
